[package]
name = "kaput-cli"
version = "2.0.1"
edition = "2021"
authors = ["David Chalifoux <mail@chalifoux.dev>"]
license = "MIT"
description = "The unofficial CLI for Put.io"
readme = "README.md"
homepage = "https://github.com/davidchalifoux/kaput-cli"
repository = "https://github.com/davidchalifoux/kaput-cli"
keywords = ["cli", "putio", "kaput", "upload", "download"]
categories = ["command-line-utilities"]
exclude = [
	".gitignore",
	".github/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
confy = "0.5.1"
serde = { version = "1.0.159", features = ["derive"] }
reqwest = { version = "0.11.16", features = ["json", "blocking", "multipart"] }
tabled = { version = "0.10.0", features = ["derive"] }
bytefmt = "0.1.7"
openssl = { version = "0.10", features = ["vendored"] }
# indicatif = "0.17.3"

[[bin]]
name = "kaput"
path = "src/main.rs"