name: Cargo Publish

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cargo Publish
        run: cargo publish --verbose
